### PR TITLE
Fix for #7 and #9

### LINKED ISSUE #7: Only one pin interrupt supported
Attaching interrupts for multiple pin change events via attachInterrupt(...) doesn't appear to work on the new nRF52840 based nano boards. 

In the simplified test case below, the first call to attachInterrupt appears to work (falling edge of IN3, or pin 6). The other ones don't work. You can change the order of the attachInterrupt calls to get a different pin change interrupt to start working, but I've only ever seen one interrupt working at a time. 

I think pins 4, 5, and 6 are actually pins P1_15, P1_13, and P1_14 on the nRF52840 (from variant.cpp), although this could be wrong (the documentation for these new nano boards is pretty lacking). Could this be because all of the inputs are on the same port? This normally isn't a restriction, e.g. when using Nordic's SDK, although I haven't used mbed on a Nordic IC. 

In any case, this seems like a bug. 

```
#define IN1 4
#define IN2 5
#define IN3 6

// LEDs
#define OUT1  22
#define OUT2  23
#define OUT3  24

int out1 = 1;
int out2 = 1;
int out3 = 0;

void in1_handler() {
  out1 = (out1 + 1) % 2;
  digitalWrite(OUT1, out1);
}

void in2_handler() {
  out2 = (out2 + 1) % 2;
  digitalWrite(OUT2, out2);
}

void in3_handler() {
  out3 = (out3 + 1) % 2;
  digitalWrite(OUT3, out3);
}

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  while(!Serial) {}
  Serial.println("setup");

  digitalWrite(OUT1, out1);
  digitalWrite(OUT2, out2);
  digitalWrite(OUT3, out3);

  pinMode(OUT1, OUTPUT);
  pinMode(OUT2, OUTPUT);
  pinMode(OUT3, OUTPUT);

  pinMode(IN1, INPUT_PULLUP);
  pinMode(IN2, INPUT_PULLUP);
  pinMode(IN3, INPUT_PULLUP);

  attachInterrupt(digitalPinToInterrupt(IN3), in3_handler, FALLING);
  attachInterrupt(digitalPinToInterrupt(IN2), in2_handler, FALLING);
  attachInterrupt(digitalPinToInterrupt(IN1), in1_handler, FALLING);
}

void loop() {
  // put your main code here, to run repeatedly:
  Serial.println("delay");
  delay(500);
}
```

### PR DESCRIPTION
**Pull request by ohazi**
Fixes #7 and #9. 

I just noticed that my libmbed.a is 57MB, while the current one is 17MB. The archive and object formats look the same, and there don't appear to be a lot of new object files -- many of the existing ones are just bigger.

### CODE REVIEW

**Comment by ohazi** [comment]
Instructions for the #7 workaround are here: https://github.com/arduino/ArduinoCore-nRF528x-mbedos/issues/7#issuecomment-528283381

Feel free to recreate the fix if you'd rather base it off of a different mbed-os release.

**Comment by facchinm** [comment]
Hi @ohazi ,
sorry for the delay but I'm just back from vacation :slightly_smiling_face: 
I have a branch already rebased on mbed-5.14 with a couple of patches applied over it (the most notable one is the revert of https://github.com/ARMmbed/mbed-os/commit/4e992cd901f8ab7241edf74910804aea3fa5e32c to shrink the library size).
Since now all the other patches are merged in mbed's master I'm going to update the procedure and release the fixes during this week.
Thanks for your effort anyway! Any feedback on build scripts and how to improve them is very appreciated (PRs too of course :wink: )

**Comment by ohazi** [comment]
No worries :-) This is a trivial enough fix that it probably makes more sense for you to apply it directly rather than forcing this PR onto whatever you're currently working on. 

I think the main thing that confused me was all of the references to "mbed-os-5.4.0-rc1" in the last few months of "Update mbed to ..." commits. The build script worked a lot better once I realized I should be using master or 5.13 / 5.14, and after I found the last few manual edits in cores/arduino/mbed. 

What was the story around 5.4.0-rc1?

**Comment by facchinm** [comment]
Hi @ohazi , both #7 and #9 should be solved in master and 1.1.2 . I'm going to close the issues and this PR.
I rebased everything on 5.14.0-rc1 with [these patches](https://github.com/arduino/ArduinoCore-nRF528x-mbedos/tree/master/patches) , will update the documentation accordingly :wink: 
Thanks a lot for the heads up!

**Pull request closed without merging**
