### PR TITLE
Backport patches from arduino/ArduinoCore-mbed

### PR DESCRIPTION
**Pull request by facchinm**
This should be the last maintenance release of this core; since this core is based on  mbed 5.x branch all functions marked for deprecation are still there; arduino/ArduinoCore-mbed, on the other hand, contains all the new stuff and should replace this core as soon as considered stable.

Reworks and includes #31 and #72

### CODE REVIEW

**Comment by rmlearney-digicatapult** [comment]
Excited!

One note - interrupts.cpp still doesn't cover all possible interrupt types (HIGH, LOW) - is it better to have the irq setting as a `switch(mode)` rather than nested `if/else` tests so it can be extended in future?

**Comment by facchinm** [comment]
Ah sorry, I just spotted an error in my last rebase; working on it now

**Comment by rmlearney-digicatapult** [comment]
@facchinm ah, if they're not supported then no worry. Thanks!

**Comment by rmlearney-digicatapult** [comment]
@facchinm this implementation in `Interrupts.cpp` doesn't seem to support CHANGE:

```c++
  // Give a default pullup for the pin, since calling InterruptIn with PinMode is impossible
   if (digitalPinToGpio(interruptNum) == NULL) {
     pinMode(interruptNum, mode == FALLING ? INPUT_PULLUP : INPUT_PULLDOWN);
   }
```

Perhaps the following?
```c++
   if (digitalPinToGpio(interruptNum) == NULL) {
     switch(mode){
          case FALLING:
               pinMode(interruptNum, INPUT_PULLUP);
               break;
          case RISING:
                pinMode(interruptNum, INPUT_PULLDOWN);
                break;
           case CHANGE:
                 pinMode(interruptNum, INPUT);
                 break;
     }
   }
```

**Comment by facchinm** [comment]
@rmlearney-digicatapult the snippet you are linking only applies is the pin has not been configured as INPUT before calling `attachInterrupt` . If you look at the `beta` branch, the implementation on CHANGE is correct https://github.com/arduino/ArduinoCore-nRF528x-mbedos/blob/beta/cores/arduino/Interrupts.cpp#L39-L48

**Comment by rmlearney-digicatapult** [comment]
What will be the default pin state if somebody doesn't configure the pin as INPUT but sets an interrupt on CHANGE?

**Comment by facchinm** [comment]
Yep, you are right! Would you mind sending a PR over `beta` branch with the commit to fix it (so we can keep the attribution) ? Thanks

**Pull request merged**
